// SPDX-License-Identifier: Apache-2.0
//! Emit the agentctl CRDs as apply-able YAML under `deploy/crds/`.
//!
//! Run from the workspace root: `cargo run -p agentctl-crdgen`. The output is
//! the ground truth installed by the Helm/Kustomize bundle (agentctl RFC 0001
//! §5). Per RFC 0005, exactly one served version (`v1alpha1`) is emitted today.

use std::fs;
use std::path::Path;

use agent_api::{Agent, AgentFleet, ModelPool};
use kube::CustomResourceExt;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = Path::new("deploy/crds");
    fs::create_dir_all(out)?;

    let header = "# Generated by `cargo run -p agentctl-crdgen` — do not edit by hand.\n";

    for (file, yaml) in [
        ("agent.yaml", serde_yaml::to_string(&Agent::crd())?),
        (
            "agentfleet.yaml",
            serde_yaml::to_string(&AgentFleet::crd())?,
        ),
        ("modelpool.yaml", serde_yaml::to_string(&ModelPool::crd())?),
    ] {
        let path = out.join(file);
        fs::write(&path, format!("{header}{yaml}"))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}
