// SPDX-License-Identifier: Apache-2.0
//! Emit the agentctl CRDs as apply-able YAML under `deploy/crds/`.
//!
//! Run from the workspace root: `cargo run -p agentctl-crdgen`. The output is
//! the ground truth installed by the Helm/Kustomize bundle (mirror it to
//! `charts/agentctl/crds/` by hand — CI's drift gate covers `deploy/crds/`).
//!
//! **Versions** (P2-1): `Agent` and `AgentFleet` serve BOTH `v1alpha1` and
//! `v1alpha2`, with **v1alpha2 as the storage version** (v1→v2 conversion is
//! lossless; v2→v1 exists only for old readers and drops v2-only fields with
//! warnings at admission). The merged CRDs carry a `spec.conversion` webhook
//! stanza pointing at the admission service's `/convert` route; cert-manager's
//! CA injector fills `caBundle` via the `cert-manager.io/inject-ca-from`
//! annotation. NOTE: Helm's `crds/` dir is not templated, so the annotation
//! and service ref assume the default `agentctl-system` namespace — a
//! custom-namespace install must patch both (documented in the chart README).
//! The registry kinds (`AgentTemplate`, `AgentClass`, `MCPService`,
//! `Supervisor`, `Organization`) are v1alpha2-native, single-version.

use std::fs;
use std::path::Path;

use agent_api::{v1alpha2, ModelPool, Organization};
use kube::CustomResourceExt;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = Path::new("deploy/crds");
    fs::create_dir_all(out)?;

    let header = "# Generated by `cargo run -p agentctl-crdgen` — do not edit by hand.\n";

    // Every kind is v1alpha2-native, single-version (v1alpha1 was dropped with
    // its conversion webhook — the whole control plane speaks v1alpha2 now).
    for (file, yaml) in [
        (
            "agent.yaml",
            serde_yaml::to_string(&v1alpha2::Agent::crd())?,
        ),
        (
            "agentfleet.yaml",
            serde_yaml::to_string(&v1alpha2::AgentFleet::crd())?,
        ),
        ("modelpool.yaml", serde_yaml::to_string(&ModelPool::crd())?),
        (
            "organization.yaml",
            serde_yaml::to_string(&Organization::crd())?,
        ),
        (
            "agenttemplate.yaml",
            serde_yaml::to_string(&v1alpha2::AgentTemplate::crd())?,
        ),
        (
            "agentclass.yaml",
            serde_yaml::to_string(&v1alpha2::AgentClass::crd())?,
        ),
        (
            "mcpservice.yaml",
            serde_yaml::to_string(&v1alpha2::MCPService::crd())?,
        ),
        (
            "supervisor.yaml",
            serde_yaml::to_string(&v1alpha2::Supervisor::crd())?,
        ),
    ] {
        let path = out.join(file);
        fs::write(&path, format!("{header}{yaml}"))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}
