// SPDX-License-Identifier: Apache-2.0
//! Emit the agentctl CRDs as apply-able YAML under `deploy/crds/`.
//!
//! Run from the workspace root: `cargo run -p agentctl-crdgen`. The output is
//! the ground truth installed by the Helm/Kustomize bundle (mirror it to
//! `charts/agentctl/crds/` by hand — CI's drift gate covers `deploy/crds/`).
//!
//! **Versions** (P2-1): `Agent` and `AgentFleet` serve BOTH `v1alpha1` and
//! `v1alpha2`, with **v1alpha2 as the storage version** (v1→v2 conversion is
//! lossless; v2→v1 exists only for old readers and drops v2-only fields with
//! warnings at admission). The merged CRDs carry a `spec.conversion` webhook
//! stanza pointing at the admission service's `/convert` route; cert-manager's
//! CA injector fills `caBundle` via the `cert-manager.io/inject-ca-from`
//! annotation. NOTE: Helm's `crds/` dir is not templated, so the annotation
//! and service ref assume the default `agentctl-system` namespace — a
//! custom-namespace install must patch both (documented in the chart README).
//! The registry kinds (`AgentTemplate`, `AgentClass`, `MCPService`,
//! `Supervisor`, `Organization`) are v1alpha2-native, single-version.

use std::fs;
use std::path::Path;

use agent_api::{v1alpha2, Agent, AgentFleet, ModelPool, Organization};
use kube::core::crd::merge_crds;
use kube::CustomResourceExt;

/// The namespace + service the conversion webhook lives in (the admission
/// server's TLS endpoint; Helm crds/ is untemplated — see module docs).
const CONVERSION_NS: &str = "agentctl-system";
const CONVERSION_SVC: &str = "agentctl-admission";
const CONVERSION_CERT: &str = "agentctl-admission";

fn with_conversion(
    mut crd: k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition,
) -> k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition {
    use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1 as apiext;
    crd.metadata
        .annotations
        .get_or_insert_with(Default::default)
        .insert(
            "cert-manager.io/inject-ca-from".to_string(),
            format!("{CONVERSION_NS}/{CONVERSION_CERT}"),
        );
    crd.spec.conversion = Some(apiext::CustomResourceConversion {
        strategy: "Webhook".to_string(),
        webhook: Some(apiext::WebhookConversion {
            conversion_review_versions: vec!["v1".to_string()],
            client_config: Some(apiext::WebhookClientConfig {
                service: Some(apiext::ServiceReference {
                    name: CONVERSION_SVC.to_string(),
                    namespace: CONVERSION_NS.to_string(),
                    path: Some("/convert".to_string()),
                    port: Some(443),
                }),
                ..Default::default()
            }),
        }),
    });
    crd
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = Path::new("deploy/crds");
    fs::create_dir_all(out)?;

    let header = "# Generated by `cargo run -p agentctl-crdgen` — do not edit by hand.\n";

    // Multi-version kinds: v1alpha1 + v1alpha2, stored at v1alpha2.
    let agent = with_conversion(merge_crds(
        vec![Agent::crd(), v1alpha2::Agent::crd()],
        "v1alpha2",
    )?);
    let fleet = with_conversion(merge_crds(
        vec![AgentFleet::crd(), v1alpha2::AgentFleet::crd()],
        "v1alpha2",
    )?);

    for (file, yaml) in [
        ("agent.yaml", serde_yaml::to_string(&agent)?),
        ("agentfleet.yaml", serde_yaml::to_string(&fleet)?),
        ("modelpool.yaml", serde_yaml::to_string(&ModelPool::crd())?),
        (
            "organization.yaml",
            serde_yaml::to_string(&Organization::crd())?,
        ),
        (
            "agenttemplate.yaml",
            serde_yaml::to_string(&v1alpha2::AgentTemplate::crd())?,
        ),
        (
            "agentclass.yaml",
            serde_yaml::to_string(&v1alpha2::AgentClass::crd())?,
        ),
        (
            "mcpservice.yaml",
            serde_yaml::to_string(&v1alpha2::MCPService::crd())?,
        ),
        (
            "supervisor.yaml",
            serde_yaml::to_string(&v1alpha2::Supervisor::crd())?,
        ),
    ] {
        let path = out.join(file);
        fs::write(&path, format!("{header}{yaml}"))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}
